defaults:
  - _self_
  - config_base

hydra:
  run:
    dir: ${output_path}/train_flux_epic

exp:
  run_func:
    _target_: experiments.epic_generative_learnable.run_epic_generative

generative_model:
  model_id: "black-forest-labs/FLUX.1-schnell"

training:
  steps: 2000
  batch_size: 32
  lr_purity: 0.001
  lr_reg: 0.01
  lambda_purity: 1.0
  lambda_reg: 0.001
  lambda_entropy: 100
  gen_steps: 20

explanations:
  top_k: 4

visualization:
  num_explanations: 5
  num_prototypes: 5