defaults:
  - _self_
  - config_base

hydra:
  run:
    dir: ${output_path}/explain

generative_model:
  model_id: "black-forest-labs/FLUX.1-schnell"
  gen_steps: 4
  guidance_scale: null

exp:
  run_func:
    _target_: experiments.explain_generative.explain_predictions

dataloader:
  shuffle: True

visualization:
  num_images: 40
  k_top: 4
  output_dir: "visualizations"
